[package]
name = "bevy-dev"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.18", features = ["png"] }
image = "0.25"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
